### PR TITLE
Midendpages

### PR DESCRIPTION
**Pull request by almsam**
I implemented 3 of 4 HTML pages

### CODE REVIEW

**Review by NMarinoGH — APPROVED** [review]
HTML and JS syntax and formatting looks very good. No errors from what I can tell

**Review by Weebtrain — APPROVED** [review]
No stand out errors, addition of Flask to the stack tbd at next meeting

**Review by MASHAR27 — APPROVED** [review]
Implemented correctly

**Review by NMarinoGH — APPROVED** [review]
Syntax and formatting is good, functions as intended, I do not see any errors

**Comment by almsam** [comment]
> No stand out errors, addition of Flask to the stack tbd at next meeting

flask added to stack, next round implemented

**Comment by almsam** [comment]
> Syntax and formatting is good, functions as intended, I do not see any errors

for the next phase of development I will need you for both DB querries & segues

**Pull request merged**
