### PR TITLE
Started a test file for all.py. 

### PR DESCRIPTION
**Pull request by NMarinoGH**
Basically the admin test file but now works for all.py. The test for processing user still doesn't work but we can fix that once the database is implemented. More tests can be added as we add more code. I'll see if I can automate this with a GitHub Action.

### CODE REVIEW

**Review by MASHAR27 — APPROVED** [review]
Amazing work!

**Review by almsam — CHANGES_REQUESTED** [review]
error on line 17, object error

one of the unit tests fails

I will commit the fixes shortly

**Comment by almsam** [comment]
> Amazing work!

there was 1 failed test & 1 error, please review the code before approving from now on

**Review by almsam — APPROVED** [review]
issues fixed, should be pushable

**Pull request merged**
