### PR TITLE
Add secure login and profile editing

### PR DESCRIPTION
**Pull request by NMarinoGH**
Logging in is now secure, and you can now edit your profile. I also included edits from the validation and visual design branches. Everything still works as far as I know.

You can check my old branch secure-login-and-add-profile-switching to see a timeline of my commits, but it did not compare them to the main branch after validation was merged.

### CODE REVIEW

**Comment by NMarinoGH** [comment]
The server page now shows a list of all members in alphabetical order, and I added a restriction to signup and profile editing so you cannot have the same username.

**Review by MASHAR27 — APPROVED** [review]
Great work !

**Comment by adash02** [comment]
Looks Good!

**Review by almsam — APPROVED** [review]
seems legit, just make sure to add a handufl of comments

**Pull request merged**
