### PR TITLE
Visual design

### PR DESCRIPTION
**Pull request by MASHAR27**
Please review the NewWebPage code

### CODE REVIEW

**Review by almsam — CHANGES_REQUESTED** [review]
Why are we removing the entire web pages directory? Keep it so we have reference to the original vision

**Review by NMarinoGH — CHANGES_REQUESTED** [review]
Formatting and design updates look good, but I don't think we should have the background GIFs.

**Review by almsam — APPROVED** [review]

**Comment by almsam** [comment]
changes made, seems legit in my book, have fun merging

**Review by Weebtrain — APPROVED** [review]
File organization looks good, good to merge

**Pull request merged**
