### PR TITLE
Create channels and enable admin functions

### PR DESCRIPTION
**Pull request by NMarinoGH**
I have enabled the following:
-You can add and delete channels, and adding a channel makes you an admin of that channel.
-You can add other users to your channels.
-Server page only displays your channels, and they link to the chat page.
-Chat page lists members organized by admin or regular user.
-Admins can kick members and set and unset members as admin.
-I also reorganized some code and added comments.
-I disabled Server tables and related foreign keys as it would be too difficult to deal with null foreign keys since we are only using one server (I didn't delete the code, I just commented it out).

### CODE REVIEW

**Comment by adash02** [comment]
We are on the right rack.

**Review by almsam — APPROVED** [review]
the SQL is outside of my area of expertise, but the rest seems legit

**Review by MASHAR27 — APPROVED** [review]
Amazing work !

**Review by adash02 — APPROVED** [review]
We are on the right rack.

**Pull request merged**
