### PR TITLE
Enable messaging and profile pages

### PR DESCRIPTION
**Pull request by NMarinoGH**
I improved the button alignments, added a function to delete messages if they are yours or you are an admin, added profile pages, and direct messaging. The minimum requirements in the TA's email are now finished.

### CODE REVIEW

**Review by MASHAR27 — APPROVED** [review]
Good work!

**Review by adash02 — APPROVED** [review]
We are getting there!

**Comment by NMarinoGH** [comment]
You can now rename channels you own.

**Comment by NMarinoGH** [comment]
Users can now rename channels they own, and I managed to fix the channel search feature.

**Review by almsam — APPROVED** [review]
looks good

**Pull request merged**
