### PR TITLE
Indexmesg

### PR DESCRIPTION
**Pull request by almsam**
abhishek made an HTML

### CODE REVIEW

**Comment by almsam** [comment]
looks good to me, just be careful with negligent merges in the future

**Review by MASHAR27 — COMMENTED** [review]
Looks good

**Comment by adash02** [comment]
Approved

**Review by NMarinoGH — COMMENTED** [review]
Formatting looks good, no errors detected

**Comment by Weebtrain** [comment]
Please move webpages into the webpage file before merging

**Comment by Weebtrain** [comment]
File sorting fixed, looks like it's good to go

**Comment by almsam** [comment]
Merging

**Pull request merged**
